### ISSUE TITLE
Diseño

### ISSUE THREAD

**Issue by GestionDHS** [GestionDHS/dhs-laberinto-js#35]
# MENU 
## GENERAL
- [x] Eliminar "Titulo de la actividad"
  - Motivo: Estará en Playground junto con la consigna - es redundante.
## Íconos Botones
- [x] Agrandar tamaño del boton "Ejecutar" con respecto a los otros.
- [x] Agregar un color a cada botón (?) y customizar el color del range de velocidad.
- [x] Agregar selectores de estado `[disabled]` a cada botón para _opacar_ o _pasar a gris_ o simil su color cuando no están disponibles
- [x] Agregar efectos a `losBotones:not([disabled]):hover` (los botones que estén clickeables cuando hover):
  - [x] Usar `cursor:pointer`
  - [x] Dar un pequeño "brillo" (borde de color o sombra iluminada, o color más llamativo, etc) y/o cambio de tamaño (con `scale` - se agranda el botón al hoverearlo).
 
Motivo: hay todo un ida y vuelta de habilitación/inhabilitación de botones que no se está pudiendo rastrear con los íconos actuales).
## Tooltips botones
- [x] Usar tooltips "hacia arriba" o "hacia abajo"; no hacia los costados.
  - Motivo: A veces "tapan" los otros botones y es dificil lograr que se cierre una tooltip para poder clickear otro botón.
  - Recurso: Explorar el [código de W3Schools](https://www.w3schools.com/css/css_tooltip.asp) que se usó para las del Juego. Ver parte de _Positioning_
  - Nota: Cuidado con las clases, usar _otras_ o ponerles un prefijo para no crashear con las de Juego.
- [x] Revisar `z-index` de las tooltips vs. z-index de la toolbox del <blockly div> (quedan detrás de ella o algo así).
---
# JUEGO

- [x] Revisar legibilidad tooltips del juego. Está muy traslúcido o "blanco sobre claro".

**Comment by PiaAchigar** [comment]
Listo, todo completo
